### PR TITLE
[Fix] Fix pipe chain start with alias lifting exceptions

### LINKED ISSUE #68: Pipe Chain Starts doesn't work with Alias Lifting Exceptions
I've noticed that pipe chain start rule isn't respected for namespaces that are excluded from alias lifting rule:

For example:
stub(Quokka.Config, :lift_alias_excluded_namespaces, fn -> MapSet.new([:Name]) end)

```elixir
defmodule MyModule do
    alias Foo.Bar

     Name.M.N.bar(x)
      |> Name.M.N.bar()

     A.B.C.foo()
end
```
currently refactors to

```elixir
defmodule MyModule do
    alias A.B.C
    alias Foo.Bar

     Name.M.N.bar(x)
      |> Name.M.N.bar()

     C.foo()
end
```

and I was assuming it'd refactor to:

```elixir
defmodule MyModule do
    alias A.B.C
    alias Foo.Bar

     x
      |> Name.M.N.bar()
      |> Name.M.N.bar()

     C.foo()
end
```

I was imagining that the alias lifting excluded namespaces shouldn't fail, proposed an example fix here: https://github.com/smartrent/quokka/pull/67

cc @emkguts would you be able to take a look at this issue and the proposed fix, thank you!

### PR DESCRIPTION
**Pull request by PranavVadrevu**
I've noticed that pipe chain start rule isn't respected for namespaces that are excluded from alias lifting rule:

For example:
stub(Quokka.Config, :lift_alias_excluded_namespaces, fn -> MapSet.new([:Name]) end)
```elixir
defmodule MyModule do
    alias Foo.Bar

     Name.M.N.bar(x)
      |> Name.M.N.bar()

     A.B.C.foo()
end
```

currently refactors to

```elixir
defmodule MyModule do
    alias A.B.C
    alias Foo.Bar

     Name.M.N.bar(x)
      |> Name.M.N.bar()

     C.foo()
end
```

and I was assuming it'd refactor to:

```elixir
defmodule MyModule do
    alias A.B.C
    alias Foo.Bar

     x
      |> Name.M.N.bar()
      |> Name.M.N.bar()

     C.foo()
end
```
I was imagining that the alias lifting excluded namespaces shouldn't fail and proposing an example fix

closes #68

### CODE REVIEW

File: lib/style/pipes.ex [hunk 1]
```diff
@@ -443,10 +443,10 @@ defmodule Quokka.Style.Pipes do
   # 'char#{list} interpolation'
   defp valid_pipe_start?({{:., _, [List, :to_charlist]}, _, _}), do: true
   # n-arity Module.function_call(...args)
-  defp valid_pipe_start?({{:., _, [{_, _, [mod]}, fun]}, _, arguments}) do
+  defp valid_pipe_start?({{:., _, [{_, _, mod_list}, fun]}, _, arguments}) do
```
Comment (emkguts) [inline lib/style/pipes.ex:446]:
```suggestion
  defp valid_pipe_start?({{:., _, [{_, _, mod_list}, fun]}, _, arguments}) when is_list(mod_list) do
```

**Review by emkguts — CHANGES_REQUESTED** [review]
One tweak and then I'l approve and release a patch. Thanks for this!

File: lib/style/pipes.ex (hunk 1 above)
Comment (PranavVadrevu) [reply lib/style/pipes.ex]: Amazing, thank you!

**Comment by PranavVadrevu** [comment]
Just merged your suggestion, thank you!

**Review by emkguts — APPROVED** [review]
✅ 🚀
