### PR TITLE
Fix alias lift

### LINKED ISSUE #61: Alias Lifting with excluded_namespaces wasn't working properly
```elixir
defmodule A do
  def do_something() do
    X.Y.Z.blah()
    X.Y.Z.blah()
  end
end
```

When we provide X.Y as a excluded_namespaces in credo.exs, it is crashing quokka. 

I have a proposed PR fix here: https://github.com/smartrent/quokka/pull/60

@emkguts Would you be able to take a look at this issue and the proposed fix?

### PR DESCRIPTION
**Pull request by emkguts**
closes #61

### CODE REVIEW

**Comment by emkguts** [comment]
@PranavVadrevu Can you verify that this works as expected for you? I tested it against one of my code bases and I fleshed out the tests, and it worked for me.

File: lib/quokka/config.ex [hunk 1]
```diff
@@ -110,8 +108,10 @@ defmodule Quokka.Config do
         large_numbers_gt: credo_opts[:large_numbers_gt] || :infinity,
         lift_alias: credo_opts[:lift_alias] || false,
         lift_alias_depth: credo_opts[:lift_alias_depth] || 0,
-        lift_alias_excluded_lastnames: MapSet.new(lift_alias_excluded_lastnames ++ @stdlib),
-        lift_alias_excluded_namespaces: MapSet.new(lift_alias_excluded_namespaces ++ @stdlib),
+        lift_alias_excluded_lastnames:
+          MapSet.new(Enum.map(lift_alias_excluded_lastnames, &String.to_atom/1) ++ @stdlib),
```
Comment (PranavVadrevu) [inline lib/quokka/config.ex:112]: For my learning, do we need to convert to atom here (I was assuming these are already atoms)

File: lib/quokka/config.ex [hunk 2]
```diff
@@ -110,8 +108,10 @@ defmodule Quokka.Config do
...
+        lift_alias_excluded_namespaces:
+          MapSet.new(Enum.map(lift_alias_excluded_namespaces, &String.to_atom/1) ++ @stdlib),
```
Comment (PranavVadrevu) [inline lib/quokka/config.ex:114]: Had a similar question here - it seemed to work for me without such a conversion cus we removed the Atom.to_string earlier

**Comment by PranavVadrevu** [comment]
> @PranavVadrevu Can you verify that this works as expected for you? I tested it against one of my code bases and I fleshed out the tests, and it worked for me. I also didn't seem to need the Elixir. prefix to get things working. If you could produce an example of where you needed to add Elixir. (as in your PR) to make it work, that would help me. 🙇‍♀️

Taking a look at this right now, thank you!

File: lib/quokka/config.ex (hunk 1 above)
Comment (PranavVadrevu) [reply lib/quokka/config.ex:112]: image

I ran into this issue of force converting an atom to an atom

**Comment by PranavVadrevu** [comment]
I think the quirk I run into (w/ "Elixir." prepended) could be explained w/ this small example: `Atom.to_string(X.Y.Z)` = "Elixir.X.Y.Z"

image
cc @emkguts

File: lib/quokka/config.ex (hunk 1 above)
Comment (emkguts) [reply lib/quokka/config.ex:112]: Based on the [Credo docs](https://hexdocs.pm/credo/Credo.Check.Design.AliasUsage.html#module-excluded_namespaces), I expect `lift_alias_excluded_lastnames` to be strings. I decided to convert them to atoms here so that the final list (`excluded_lastnames ++ @stdlib`) is all atoms.

**Comment by emkguts** [comment]
> I think the quirk I run into (w/ "Elixir." prepended) could be explained w/ this small example: `Atom.to_string(X.Y.Z)` = "Elixir.X.Y.Z"
> 
> image
> cc @emkguts

Ah okay, that makes sense. I don't think your code is representative of what's happening when code gets processed. Without more context of what you're trying to do, I can't give a better explanation. But if you look at the below, it doesn't add `Elixir.` as a prefix. And, when you have a module named `defmodule X.Y.Z`, this will get encoded in the AST as `[:X, :Y, :Z]`. 

Screenshot 2025-04-01 at 7 01 06 PM

File: lib/quokka/config.ex (hunk 1 above)
Comment (PranavVadrevu) [reply lib/quokka/config.ex:112]: Ah this is my bad, I was used to writing modules as atoms, this no longer crashes once I treat them as strings, thank you!

**Comment by PranavVadrevu** [comment]
Ah yep, after you other comment, I'm guessing the issue wasn't with the code getting processed but rather that I was passing my namespaces in Credo as Atoms (which had the Elixir prefix prepended when converted to strings - but Credo looks like it normally took in list of strings for that in the first place - which avoids this issue)

**Comment by PranavVadrevu** [comment]
Thank you @emkguts - I can confirm your fix works - the main difference and self-induced bug around "Elixir." prepending was from me defining excluded_namespaces at atoms rather than Strings, thanks a lot for the help!

**Comment by emkguts** [comment]
> Thank you @emkguts - I can confirm your fix works - the main difference and self-induced bug around "Elixir." prepending was from me defining excluded_namespaces at atoms rather than Strings, thanks a lot for the help!

@PranavVadrevu I think you still identified a bug -- I was able to reproduce a crash because the namespaces were strings while the `stdlib` list was all  atoms. And, your issue pushed me to make the tests more robust. Thanks so much for your contribution! 😄 I'll do a release shortly.
